### ISSUE TITLE
Fix `every_third_instance_of_weekday_in_month_for_3_months` test

### ISSUE THREAD

**Issue by ralpha** [fmeringdal/rust-rrule#33] opened 2021-10-15 23:23 UTC
The rrule 
```
DTSTART;TZID=America/New_York:19970904T090000
RRULE:FREQ=MONTHLY;COUNT=3;BYDAY=TU,WE,TH;BYSETPOS=3
```
is incorrectly validated or/and produces incorrect results.

Expected:
```
1997-09-04T09:00:00-04:00
1997-10-07T09:00:00-04:00
1997-11-06T09:00:00-05:00
```

Current result (incorrect):
```
1997-10-06T09:00:00-04:00
1997-11-05T09:00:00-05:00
1997-12-03T09:00:00-05:00
```

See test: `every_third_instance_of_weekday_in_month_for_3_months`
Test source: https://icalendar.org/iCalendar-RFC-5545/3-8-5-3-recurrence-rule.html

**Comment by fmeringdal** [comment] 2021-10-16 12:13
Duplicate of #34. See [comment](https://github.com/fmeringdal/rust-rrule/issues/34#issuecomment-944906249)

**Closed** 2021-10-16 12:14 UTC
Labels: bug, help wanted
